# Generated by Django 3.0.3 on 2020-02-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=125,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Name",
                    ),
                ),
                (
                    "national_pokedex_number",
                    models.PositiveSmallIntegerField(
                        verbose_name="National Pokédex number"
                    ),
                ),
                ("type_1", models.CharField(max_length=50, verbose_name="Type 1")),
                (
                    "type_2",
                    models.CharField(max_length=50, null=True, verbose_name="Type 1"),
                ),
                ("total", models.PositiveSmallIntegerField(verbose_name="Total")),
                ("hp", models.PositiveSmallIntegerField(verbose_name="HP")),
                ("attack", models.PositiveSmallIntegerField(verbose_name="Attack")),
                ("defense", models.PositiveSmallIntegerField(verbose_name="Defense")),
                (
                    "sp_attack",
                    models.PositiveSmallIntegerField(verbose_name="SP Attack"),
                ),
                (
                    "sp_defense",
                    models.PositiveSmallIntegerField(verbose_name="SP Defense"),
                ),
                ("speed", models.PositiveSmallIntegerField(verbose_name="Speed")),
                (
                    "generation",
                    models.PositiveSmallIntegerField(verbose_name="Generation"),
                ),
            ],
        ),
    ]
