# Generated by Django 3.0.4 on 2020-03-21 19:18

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0002_auto_20200321_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('zip_code_shorted', models.SmallIntegerField(max_length=3, verbose_name='Zip code 3 chars')),
                ('symptoms', models.ManyToManyField(to='datastore.Symptom')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
