# Generated by Django 3.0.4 on 2020-03-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0003_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='zip_code_shorted',
            field=models.PositiveSmallIntegerField(max_length=3, verbose_name='Zip code 3 chars'),
        ),
    ]
