# Generated by Django 3.0.4 on 2020-03-21 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0005_auto_20200321_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='zip_code_shorted',
            new_name='zip_code_shortened',
        ),
    ]
