# Generated by Django 3.0.4 on 2020-03-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0007_auto_20200321_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='zip_code_shortened',
            field=models.PositiveIntegerField(verbose_name='Zip code 3 chars'),
        ),
    ]
