# Generated by Django 3.0.4 on 2020-03-22 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0008_auto_20200322_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='zip_code_shortened',
            new_name='zip_code',
        ),
    ]
