# Generated by Django 3.0.4 on 2020-03-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0010_auto_20200323_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='zip_code',
            field=models.PositiveIntegerField(verbose_name='Zip code'),
        ),
    ]
