# Generated by Django 3.0.4 on 2020-03-24 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0012_auto_20200324_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='zip_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datastore.ZIPCode'),
        ),
    ]
