# Generated by Django 3.0.4 on 2020-03-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0013_report_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='zip_code',
            field=models.PositiveIntegerField(unique=True, verbose_name='Zip code'),
        ),
    ]
