# Generated by Django 3.0.4 on 2020-03-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0014_auto_20200324_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='zip_code_str',
            field=models.PositiveIntegerField(null=True, verbose_name='Zip code'),
        ),
    ]
